# Creating NumPy Arrays

In [ ]:
overview: NumPy: Numpy is a numerical computation library used for all the numerical calculations and also for the 
                  scientific computation. It stands as a foundational library to all remaining libraries.
    
numpy stands for numerical python ==== num-py.

we can also perform the statisical computing by using the numpy.


Data type of NumPy: NumPy is having a datatypr called as an ndarray. 

overview of Ndarray =====> num of dimensions array..

In [ ]:
understanding: Array is similar like a list.
    
Interview: What is diff btw array and a list?
           if given a choice to you which one you would be preffering?

Array----> internal implimentations and working in very efficient in a array comparing to list.
        

In [ ]:
# How to install numpy.

In [15]:
!pip install numpy 

requirment already statisfied:numpy in/opt/anaconda3/lib/pyhton3./site-packages(1.19.2)
    
np stands for numpy

SyntaxError: invalid syntax (<ipython-input-15-556392d7db22>, line 3)

In [8]:
import numpy as np

## 1. Create an array from a regular python list (or) tuple using the array function

In [12]:
array_one = np.array([1,2,3,4])#this is the standard format of declartion...!
array_one

array([1, 2, 3, 4])

In [13]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [ ]:
# to confirm and validate the datatype.....!

In [16]:
type(array_two)

numpy.ndarray

In [ ]:
(3,4)# 3 rows and 4 cols

### 2.NumPy offers several functions to create arrays with initial placeholder content

     create an array of zeros with desired shape(x,y)
     
       *x == number of rows
       *y == number of columns in array

In [17]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Note: internal implimentation of an array is float (decimal numbers)

In [18]:
array_of_ones = np.ones((5,3))
array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
int16, int32, int64

#### Use dtype in order to specify the data type

In [20]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [21]:
array_empty = np.empty((2,3))
array_empty

array([[9.34577196e-307, 9.34598246e-307, 1.60218491e-306],
       [1.69119873e-306, 1.24611673e-306, 1.05699581e-307]])

In [ ]:
# np.eye()creates an eyedentity matrix

In [22]:
array_eye = np.eye(5) #5*5 matrix
array_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#req : create an array of even numbers till 20

#### 3.To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.


     arange(start,stop,step,dtype)

In [24]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#Note: last value is always exclusive....!