# It also accepts float arguments.

In [2]:
import numpy as np

In [4]:
array_of_floats = np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [5]:
# Lineral array ----> single line
# Two dimensional array ---> 2lines
# 3 dimensional array ----> 3lines #(x,y,z)

## Two Dimensional Arrays

In [6]:
array_2d = np.array([(2,4,6),(3,5,7)]) #(x,y)
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [7]:
array_2d.shape

(2, 3)

### Using reshape to create n dimensional arrays.

In [8]:
np.arange(6) #(x)

array([0, 1, 2, 3, 4, 5])

In [9]:
array_nd = np.arange(6).reshape(3,2)  #3*2=6   #4*3=12
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

#### The reshape will only take arguments that multiply to the number in arange function. For example:for arange(8), the possible combinations for reshape are (2,4),(4,2),(2,2,2)
