# Iterating:

In [1]:
import numpy as np

## 1D Arrays:

In [2]:
a = np.arange(11)**2       #squaring operation
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [ ]:
I is temproray verbal.

In [3]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [3]:
import numpy as np

## Multi-Dimensional Arrays

### Iterating over multi-dimensional arrays is done with respect to the first axis:

In [7]:
students = np.array([['Alice','Beth','Cathy','Dorothy'],
                     [65,78,90,81],
                     [71,82,79,92]])

#### Each iteration will be over the rows of the array 

In [12]:
for i in students:      #rows wise iteration...!
    print ('i = ',i)

i =  ['Alice' 'Beth' 'Cathy' 'Dorothy']
i =  ['65' '78' '90' '81']
i =  ['71' '82' '79' '92']


## Flatten a multi-dimensional array

#### If one wants to perform an operation on each element in the array, one can use the faltten function which will flatten the array to a single dimension.

#### By default, the falttening will occour row-wise (also known as C order). 

In [13]:
for element in students.flatten():
    print(element)

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


In [14]:
for x in students.flatten():
    print(x)

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


## Fortan Order Flattening

#### To flatten a 2D array column-wise, use the fortan order

In [ ]:
F = Fortan oder.

In [15]:
for element in students.flatten(order='F'):
    print(element)

Alice
65
71
Beth
78
82
Cathy
90
79
Dorothy
81
92


# nditer

#### Efficient multi-dimension iterator object to iterate over arrays.

In [ ]:
*nditer is only used in numpy.

In [17]:
import numpy as np

In [20]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Default iteration behaviour in C order

#### This is row-wise iteration, similar to iterating over a C-order flattenened array.

In [ ]:
Flatten method is used global wise

In [21]:
for i in np.nditer(x):     #np.nditer(x)
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
dtype = np.int16, dtype = np.int32------>typecasting.

## Fortan Order

#### This is like iterating over an array which has been flattened column-wise.

In [22]:
for i in np.nditer(x,order = 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


# Flags

### There are a numbers of flags which we can pass as a list to nditer

In [24]:
for i in np.nditer(x, order = 'F', flags = ['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


## Modifying Array Values

#### By default, the nditer treats the input array as a read-only object. To modify the array elements, you must specify either read- write (or) write only mode. This is controlled with pre-operand flags.

### Writing on a read-only array results in an error.

In [25]:
for arr in np.nditer(x):
    arr[...] = arr * arr

ValueError: assignment destination is read-only

### We set the ops_flag to makethe array read-write.

In [27]:
for arr in np.nditer(x, op_flags = ['readwrite']):
    arr[...] = arr * arr

In [28]:
x

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])